# 2026-09-18, version 4.1.3-beta: ASGSR, Alexey Emanov
#@PydevCodeAnalysisIgnore
"""clean_database

Revision ID: 81e1ccb617ce
Revises: a30b33c0e533
Create Date: 2021-01-05 10:57:00.509613

"""
from alembic import op
from sqlalchemy.orm.session import Session
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from yasmine.app.models import UserLibraryModel, XmlNodeAttrValModel, XmlNodeInstModel, XmlModel

revision = '81e1ccb617ce'
down_revision = 'a30b33c0e533'
branch_labels = None
depends_on = None


def upgrade():
    # Destructive deletes were removed: this revision stays in the chain for
    # existing databases, but new installs must not wipe inventory data.
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
